---
# Configuración regional
system_timezone: "Europe/Stockholm"
system_locale: "sv_SE.UTF-8"
system_keyboard: "se"

# Usuarios (puedes añadir tu usuario de despliegue aquí)
admin_user: "deploy"

# Puertos base para todos los servidores
base_firewall_services:
  - ssh
  - http
  - https