- name: Eliminar Host de Zabbix
  hosts: localhost
  connection: local
  tasks:
    - name: Remover monitoreo de la VM
      community.zabbix.zabbix_host:
        server_url: http://192.168.1.50/zabbix
        login_user: Admin
        login_password: zabbix_password
        host_name: "{{ vm_to_delete }}"
        status: absent