---
# IP of your Zabbix Server (The VM we just created)
zabbix_server_ip: "192.168.1.165"
zabbix_version: "7.0"
repo_rpm_url: "https://repo.zabbix.com/zabbix/7.0/alma/10/x86_64/zabbix-release-latest.el10.noarch.rpm"