---
- name: Install Zabbix Server
  hosts: all
  become: yes

  vars:
    ansible_user: deploy
    ansible_ssh_private_key_file: "~/.ssh/deploy_key"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    db_password: "Password"
    timezone: "Europe/Stockholm"
    repo_rpm_url: "https://repo.zabbix.com/zabbix/7.0/alma/9/x86_64/zabbix-release-latest.el9.noarch.rpm"
    
    # CENTRALIZACIÓN DE CREDENCIALES ZABBIX API
    zbx_api_user: "Admin"
    zbx_api_pass: "zabbix"
    zbx_api_path: "zabbix"
    

    # CENTRALIZACIÓN DE CREDENCIALES ZABBIX API
    zbx_api_user_email: "alexeimartinez.rod@gmail.com"
    zbx_admin_user_username: "Alexei"
    zbx_admin_user_name: "Alexei Martinez"
    zbx_admin_user_surname: "AlexeiMR"
    zbx_admin_user_password: "AlexPass123"

  handlers:
    - name: restart zabbix-services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop: [zabbix-server, zabbix-agent2, httpd, mariadb]

  tasks:
    - name: Ensure Base configuration is installed
      include_tasks: default_config.yml
      
    
    # ---------------------------------------------------------
    #  System Preparation
    # ---------------------------------------------------------
    - name: Wait for cloud-init to finish
      ansible.builtin.command: cloud-init status --wait
      changed_when: false
      failed_when: false

    - name: Install Zabbix Official Repository
      ansible.builtin.dnf:
        name: "{{ repo_rpm_url }}"
        state: present
        validate_certs: false
        disable_gpg_check: true

   
    # ---------------------------------------------------------
    #  Database Engine Installation
    # ---------------------------------------------------------
    - name: Install MariaDB Server and MySQL Python dependencies
      ansible.builtin.dnf:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present

    - name: Ensure MariaDB is started and enabled
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: true

    # ---------------------------------------------------------
    #  Zabbix Database & User Creation
    # ---------------------------------------------------------
    - name: Create Zabbix database
      community.mysql.mysql_db:
        name: zabbix
        encoding: utf8mb4
        collation: utf8mb4_bin
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create Zabbix database user
      community.mysql.mysql_user:
        name: zabbix
        password: "{{ db_password }}"
        priv: 'zabbix.*:ALL'
        login_unix_socket: /var/lib/mysql/mysql.sock

     
    # ---------------------------------------------------------
    #  Zabbix Core Installation
    # ---------------------------------------------------------
    - name: Install Zabbix Server, Web Frontend, and Agent 2
      ansible.builtin.dnf:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-selinux-policy
          - zabbix-agent2
          - firewalld
        state: present

    - name: Import initial Database schema
      ansible.builtin.shell: |
        zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql -uzabbix -p{{ db_password }} zabbix
      args:
        creates: /var/lib/mysql/zabbix/hosts.ibd

    
    # ---------------------------------------------------------
    #  Configuration & Templating
    # ---------------------------------------------------------
    - name: Configure Database password in zabbix_server.conf
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: "DBPassword={{ db_password }}"
      notify: restart zabbix-services

    - name: Configure Zabbix Frontend (PHP Template)
      ansible.builtin.template:
        src: templates/zabbix.conf.php.j2
        dest: /etc/zabbix/web/zabbix.conf.php
        owner: apache
        group: apache
        mode: '0644'

    - name: Set PHP Timezone in php.ini
      ansible.builtin.lineinfile:
        path: /etc/php.ini
        regexp: '^;date.timezone ='
        line: "date.timezone = {{ timezone }}"
      notify: restart zabbix-services

    
    # ---------------------------------------------------------
    #  Security & Firewall
    # ---------------------------------------------------------
    - name: Open Firewall ports
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https
        - zabbix-server

    - name: Allow Apache to connect to Database (SELinux)
      ansible.posix.seboolean:
        name: httpd_can_network_connect_db
        state: true
        persistent: true

    - name: Allow Apache to connect to Zabbix Server network (SELinux)
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true

    - name: Ensure Zabbix Agent 2 Configuration
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^ServerActive=', line: 'ServerActive=127.0.0.1' }
        - { regexp: '^Hostname=', line: "Hostname={{ inventory_hostname }}" }
      notify: restart zabbix-services

    - name: Install pip and zabbix-api
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install zabbix-api python package
      ansible.builtin.pip:
        name: zabbix-api

    # ---------------------------------------------------------
    #  Activation & API
    # ---------------------------------------------------------
    - name: Force handlers
      ansible.builtin.meta: flush_handlers
    
    - name: Wait for Zabbix Web
      ansible.builtin.wait_for:
        port: 80
        host: "{{ ansible_host }}"
        delay: 5
        timeout: 90
        
    - name: "Configure Zabbix Autoregistration Action"
      community.zabbix.zabbix_action:
        name: "Auto-registration for Hyper-V Nodes"
        event_source: "auto_registration"
        state: present
        status: enabled
        esc_period: "1h"
        conditions:
          - type: "host_metadata"
            operator: "contains"
            value: "zabbix_node_sw"
        operations:
          - type: "add_host"
          - type: "add_to_host_group"
            host_groups: ["Linux servers"]
          - type: "link_to_template"
            templates: ["Linux by Zabbix agent"]
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_zabbix_url_path: "{{ zbx_api_path }}"
        ansible_host: "{{ ansible_host }}"
        ansible_httpapi_user: "{{ zbx_api_user }}"
        ansible_httpapi_pass: "{{ zbx_api_pass }}"
        ansible_user: "{{ zbx_api_user }}"
      delegate_to: localhost
      run_once: true    
    
    # ---------------------------------------------------------
    #  BONUS: Create trigger and Admin User info
    # ---------------------------------------------------------
    - name: "Configure Admin User Group and Media"
      community.zabbix.zabbix_user:
        username: "{{ zbx_admin_user_username }}"
        name: "{{ zbx_admin_user_name }}"
        surname: "{{ zbx_admin_user_surname }}"
        passwd: "{{ zbx_admin_user_password }}" 
        usrgrps:
          - Guests
          - Disabled
          - Zabbix administrators
        lang: en_US
        theme: blue-theme
        autologin: false
        autologout: "0"
        refresh: "30"
        rows_per_page: "200"
        after_login_url: ""
        user_medias:
          - mediatype: Email
            sendto:
              - "{{ zbx_api_user_email }}"
            period: 1-7,00:00-24:00
            severity:
              not_classified: false
              information: true
              warning: true
              average: true
              high: true
              disaster: true
            active: true
        state: present
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_zabbix_url_path: "{{ zbx_api_path }}"
        ansible_host: "{{ ansible_host }}"
        ansible_httpapi_user: "{{ zbx_api_user }}"
        ansible_httpapi_pass: "{{ zbx_api_pass }}"
        ansible_user: "{{ zbx_api_user }}"
      delegate_to: localhost
      run_once: true
      
    - name: "Configure Zabbix Alerts: High CPU & Memory"
      community.zabbix.zabbix_action:
        name: "Alert: High Resource Usage on Nodes"
        event_source: "trigger"
        state: present
        status: enabled
        esc_period: "1h"
        conditions:
          - type: "trigger_severity"
            operator: ">="
            value: "average"
        operations:
          - type: "send_message"
            media_type: "Email"
            send_to_groups: ["Zabbix administrators"]
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_zabbix_url_path: "{{ zbx_api_path }}"
        ansible_host: "{{ ansible_host }}"
        ansible_httpapi_user: "{{ zbx_api_user }}"
        ansible_httpapi_pass: "{{ zbx_api_pass }}"
        ansible_user: "{{ zbx_api_user }}"
      delegate_to: localhost
      run_once: true